name       : libxslt
version    : 1.1.35
release    : 13
source     :
    - https://gitlab.gnome.org/GNOME/libxslt/-/archive/v1.1.35/libxslt-v1.1.35.tar.bz2 : 2da1c2954f8a4e844f9d4e9110d1b31d45e7a5f8e9edc61823984861505e6e5d
license    : MIT
component  : system.base
emul32     : yes
summary    : GNOME XSLT Library
description: |
    The libxslt package contains XSLT libraries used for extending libxml2 libraries to support XSLT files.
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
patterns   :
    - devel :
        - /usr/share/doc/
        - /usr/share/gtk-doc/
        - /usr/bin/xslt-config
        - /usr/share/man/man3/
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-python"
    fi
    %reconfigure --disable-static $exOpts
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
