name       : libxslt
version    : 1.1.29
release    : 6
source     :
    - http://xmlsoft.org/sources/libxslt-1.1.29.tar.gz : b5976e3857837e7617b29f2249ebb5eeac34e249208d31f1fbf7a6ba7a4090ce
license    :
    - LGPL-2.1
summary    : GNOME XSLT Library
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
patterns   :
    - devel:
        - /usr/bin/xslt-config
        - /usr/share/man/man3/
emul32     : yes
description: |
    The libxslt package contains XSLT libraries used for extending libxml2 libraries to support XSLT files.
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-python"
    fi
    %configure --prefix=/usr --disable-static $exOpts
build      : |
    %make
install    : |
    %make_install
