name       : libxslt
version    : 1.1.32
release    : 11
source     :
    - https://github.com/GNOME/libxslt/archive/v1.1.32.tar.gz : 2d9123cd4f142905fe2d281a5318ef74a9217bd17501fbc4213460fbf747d01a
license    : MIT
component  : system.base
emul32     : yes
summary    : GNOME XSLT Library
description: |
    The libxslt package contains XSLT libraries used for extending libxml2 libraries to support XSLT files.
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
patterns   :
    - devel :
        - /usr/share/doc/
        - /usr/bin/xslt-config
        - /usr/share/man/man3/
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-python"
    fi
    %reconfigure --disable-static $exOpts
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
