name       : libxslt
version    : 1.1.32
release    : 10
source     :
    - http://xmlsoft.org/sources/libxslt-1.1.32.tar.gz : 526ecd0abaf4a7789041622c3950c0e7f2c4c8835471515fd77eec684a355460
license    : MIT
component  : system.base
emul32     : yes
summary    : GNOME XSLT Library
description: |
    The libxslt package contains XSLT libraries used for extending libxml2 libraries to support XSLT files.
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
patterns   :
    - devel :
        - /usr/share/doc/
        - /usr/bin/xslt-config
        - /usr/share/man/man3/
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-python"
    fi
    %configure --disable-static $exOpts
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
