name       : libxslt
version    : 1.1.29
release    : 9
source     :
    - http://xmlsoft.org/sources/libxslt-1.1.29.tar.gz : b5976e3857837e7617b29f2249ebb5eeac34e249208d31f1fbf7a6ba7a4090ce
license    : LGPL-2.1
component  : system.base
emul32     : yes
summary    : GNOME XSLT Library
description: |
    The libxslt package contains XSLT libraries used for extending libxml2 libraries to support XSLT files.
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
patterns   :
    - devel :
        - /usr/bin/xslt-config
        - /usr/share/man/man3/
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2015-9019.patch
    %patch -p1 < $pkgfiles/security/cve-2017-5029.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-python"
    fi
    %configure --prefix=/usr --disable-static $exOpts
build      : |
    %make
install    : |
    %make_install
